# reverse proxy rule

[[redirects]]
  from = "/api/*"

  to = "https://mail-mind-beta.onrender.com/api/:splat"

  status = 200

  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200